spring:
  application:
    name: orders
  datasource:
    url: jdbc:postgresql://localhost:5432/sandbox
    driverClassName: org.postgresql.Driver
    username: postgres
    password: mysecretpassword
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: create-drop
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true

server:
  port: ${port:8080}