FROM postgres:latest

ENV POSTGRES_DB=sandbox
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=mysecretpassword

# Copy SQL script to the docker-entrypoint-initdb.d directory
COPY schemas.sql /docker-entrypoint-initdb.d/


