---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-burger-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiap-burger-app
  template:
    metadata:
      labels:
        app: fiap-burger-app
    spec:
      terminationGracePeriodSeconds: 90
      automountServiceAccountToken: false
      containers:
        - name: fiap-burger-app
          image: gm50x/fiap-burger:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: "fiap-burger-pgsecrets"
          env:
            - name: TZ
              value: "America/Sao_Paulo"
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/dev/fiap-burger"
            - name: MERCADOPAGO_ENABLED
              value: "false"
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: "1800m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "512Mi"
          livenessProbe:
            initialDelaySeconds: 30
            failureThreshold: 3
            periodSeconds: 15
            httpGet:
              path: /dev/fiap-burger/api/v1/followup
              port: 8080
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            tcpSocket:
              port: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fiap-burger-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fiap-burger-app
  minReplicas: 1
  maxReplicas: 3
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Percent
          value: 200
          periodSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 200
---
apiVersion: v1
kind: Service
metadata:
  name: fiap-burger-app-nlb-srv
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  selector:
    app: fiap-burger-app
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
