---
apiVersion: v1
kind: Secret
metadata:
  name: fiap-burger-pgsecrets
data:
  # echo -n "secret-value" | base64 -w 0
  SPRING_DATASOURCE_URL: ""
  SPRING_DATASOURCE_USERNAME: ""
  SPRING_DATASOURCE_PASSWORD: ""
